### ISSUE TITLE
Thoughts on a full fork?

### ISSUE THREAD

**Issue by zenspider** [adamsanderson/sexp_path#17]
I'm guessing this is mostly EOL'd for you. I'd like to incorporate its functionality into seattlerb/sexp_processor and extend it to have more full matching capabilities (anchors and groups).

Thoughts?

**Comment by adamsanderson** [comment]
That would be great, the use case I once had turned out to be more easily solved with a regexp ;)  I mostly hold onto this to remind myself that I can create software I can't reason about ;)

**Comment by adamsanderson** [comment]
I've added you as a collaborator on this, let me know where you'd like to take it, and I'll help out as time permits.

**Comment by zenspider** [comment]
Thanks.

I have 3 more commit branches that I am probably NOT going to issue pull requests for. They're divergent changes (seattle style, minitest, etc) and don't enhance the project. I'll probably work on stripping this down to what I understand and then merging directly into `Sexp` and friends.

**Comment by adamsanderson** [comment]
Sounds good. Feel free to get in touch with me through github or by email and I'll try to clarify whatever I can still wrap my head around.  Maybe I can drop by one of the seattle.rb meet ups.

**Comment by zenspider** [comment]
That would be awesome. You definitely should.
